version: '3.8'

services:
  something-secret:
    build: ./
    container_name: something-secret
    image: something-secret:latest
    restart: unless-stopped
    tty: true
    env_file:
      - ./src/.env.development.local
